version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
    post_build:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/spring-security-sample-jsug-201908-1.0.0.jar

